# Use when Flutter web is already built on the host:
#   flutter build web --release
#   docker build -f Dockerfile.prebuilt -t consul-web .
FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY build/web /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
